### ISSUE TITLE
failed  compiling

### ISSUE THREAD

**Issue by bhzhu203** [alienrobotarmy/ctunnel#12]
make -C src/
make[1]: Entering directory `/root/ctunnel-master/src'
--------------------------------------------------------------------------------
                          ctunnel build using OPENSSL
--------------------------------------------------------------------------------
gcc -g -Wall -Wextra -Wcast-align -Wshadow -Wstrict-prototypes -O2  -DHAVE_OPENSSL -I../include -I./include -DHAVE_TUNTAP   -c -o ctunnel.o ctunnel.c
gcc -g -Wall -Wextra -Wcast-align -Wshadow -Wstrict-prototypes -O2  -DHAVE_OPENSSL -I../include -I./include -DHAVE_TUNTAP   -c -o net.o net.c
gcc -g -Wall -Wextra -Wcast-align -Wshadow -Wstrict-prototypes -O2  -DHAVE_OPENSSL -I../include -I./include -DHAVE_TUNTAP -o ctunnel cidr.o comp.o crypto.o ctunnel.o exec.o jtok.o keyfile.o log.o net.o opt.o stats.o tun.o tunnel_loop.o tunnel_thread.o vpn_handshake.o vpn_loop.o vpn_thread.o -lz -lpthread -lutil -lc -lcrypto 
ctunnel.o: In function `main':
/root/ctunnel-master/src/ctunnel.c:31: multiple definition of `main'
cidr.o:/root/ctunnel-master/src/cidr.c:75: first defined here
net.o: In function `in_subnet':
/root/ctunnel-master/src/net.c:24: multiple definition of `in_subnet'
cidr.o:/root/ctunnel-master/src/cidr.c:24: first defined here
net.o: In function `cidr_to_mask':
/root/ctunnel-master/src/net.c:40: multiple definition of `cidr_to_mask'
cidr.o:/root/ctunnel-master/src/cidr.c:40: first defined here
collect2: ld returned 1 exit status
make[1]: *** [ctunnel] Error 1
make[1]: Leaving directory `/root/ctunnel-master/src'
make: *** [all] Error 2

But seems version 0.7 is fine

**Comment by alienrobotarmy** [comment]
I've just updated the master branch. Please pull and try to compile.

```
git pull origin master
```

**Comment by bhzhu203** [comment]
Thanks it is sloved .
