### ISSUE TITLE
how to make ctunnel with no cryptographic /  encrypting

### ISSUE THREAD

**Issue by bhzhu203** [alienrobotarmy/ctunnel#14]
"ctuunel also is a plain tunnel" But I dont find the option to disable the cryptographic.

I want to use the ctuunel VPN fuction to forward my encryption content and dont want it to be encrypted twice.

Do you have any idea ? Thanks.

**Comment by alienrobotarmy** [comment]
Simply pass the `-C plain` option to instruct the crypto linbrary NOT to encrypt.

Example:
```
./ctunnel -n -c -l 127.0.0.1:2202 -f 10.0.0.2:22 -C plain
```

This will proxy (without encryption) TCP connections from 127.0.0.1/2022 to 10.0.0.2/22

- README.md updated
