### ISSUE TITLE
ctunnel "client" option core dumped

### ISSUE THREAD

**Issue by bhzhu203** [alienrobotarmy/ctunnel#15]
example1:
./ctunnel  -V  -c -n -C rc4
ctunnel 0.7 Copyright (C) 2008-2014 Jess Mahan
Enter Key [16 Characters]: 1234567891234567
Enter IV  [16 Characters]: 1234567891234567
[ctunnel] ctunnel 0.7 starting
[ctunnel] TCP [OpenSSL] VPN using rc4
Segmentation fault

example2:
./ctunnel  -V -f 127.0.0.1:8889  -c -t 2 -n -C plain
ctunnel 0.7 Copyright (C) 2008-2014 Jess Mahan
[ctunnel] ctunnel 0.7 starting
Segmentation fault (core dumped)

example3:
./ctunnel  -V -l 127.0.0.1:8889  -c -t 2 -n -C rc4
ctunnel 0.7 Copyright (C) 2008-2014 Jess Mahan
[ctunnel] ctunnel 0.7 starting
[ctunnel] TCP [OpenSSL] VPN using rc4
Segmentation fault (core dumped)

[coredump.tar.gz](https://github.com/alienrobotarmy/ctunnel/files/4903068/coredump.tar.gz)

1. the version info is not updated ,still 0.7
2. client option always crash with " -C plain" option
3.
./ctunnel  -V -f 127.0.0.1:8889  -c -t 2 -n -C plain   bad
./ctunnel  -V -f 127.0.0.1:8889  -c -t 2 -n -C cr4      good

4. sometimes client is not conected with server , crashed  (not sure)

5. -c option with  -l (not -f)  crashed

**Comment by alienrobotarmy** [comment]
I noticed that in every example you didn't specify a listen address with `-l`.

You should have received an error message about missing the `-l` option, which is a bug. But just be aware that without a listen address ctunnel will not function properly.

**Comment by alienrobotarmy** [comment]
I will have an update for these issues in a few hours

**Comment by alienrobotarmy** [comment]
I have updated `master` with what I believe should address all of your issues.

Please also be advised that when using `-V` (VPN Mode), you should also specify `-U` (UDP Mode). VPN's don't function well using TCP.
