### ISSUE TITLE
IPv6 compatible?

### ISSUE THREAD

**Issue by Keyshoun** [alienrobotarmy/ctunnel#17]
Is ctunnel compatible with IPv6?
Trying to proxy with ctunnel to an IPv6 host, but ctunnel is not binding to IPv6, instead it is listening on 255.255.255.255.
What is the syntax to use IPv6?
[IPv6-ip]:port

**Comment by alienrobotarmy** [comment]
ipv6 support is not in ctunnel yet.

I will add it to the TODO list!

**Comment by Keyshoun** [comment]
Okay,
that`s great thanks.
