### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by foaes** [alienrobotarmy/ctunnel#18]
/usr/bin/ld: log.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: log.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: net.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: opt.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: stats.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: tun.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
/usr/bin/ld: tunnel_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
/usr/bin/ld: tunnel_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: vpn_handshake.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: vpn_loop.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: multiple definition of `hosts'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:229: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: multiple definition of `do_encrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:233: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: multiple definition of `do_decrypt'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:234: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: multiple definition of `crypto_init'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:235: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: multiple definition of `crypto_deinit'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:236: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: multiple definition of `crypto_reset'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:237: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: multiple definition of `mutex'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:207: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: multiple definition of `threads'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:214: first defined here
/usr/bin/ld: vpn_thread.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: multiple definition of `clients'; comp.o:/home/Reel/Downloads/tunnel/ctunnel/src/../include/ctunnel.h:230: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:31: ctunnel] Error 1
make[1]: Leaving directory '/home/Reel/Downloads/tunnel/ctunnel/src'
make: *** [Makefile:3: all] Error 2

**Comment by alienrobotarmy** [comment]
Seems like there is something up with your source tree.

Can you try a couple things:
1) `make clean && make`
or
2) Create a fresh `git clone` of the `master` branch of this repo and try `make`

**Comment by alienrobotarmy** [comment]
What OS / Version are you trying to build on?

I'm seeing the same thing with `Ubuntu 22.04.1 LTS`

I'll see if I can fix this today

**Comment by alienrobotarmy** [comment]
Please clone `master` branch and try to build again. This should be fixed

**Comment by foaes** [comment]
It Worked, Thank you.
There are many repositories have the same issue on Ubuntu 22, I guess it because of the new GLIBC version.

**Comment by foaes** [comment]
Have you tested the VPN on Ubuntu 22? I get the error below when connecting the client.

Client Terminal:
```
ctunnel 0.8 Copyright (C) 2008-2020 Jess Mahan
[ctunnel] ctunnel 0.8 starting
[ctunnel] UDP [OpenSSL] VPN using aes-128-cfb
[ctunnel] UDP Connect to 192.168.1.100:1024
[ctunnel] Sending hostname asas-Standard-PC-Q35-ICH9-2009
[ctunnel] Problem with remote endpoint
[ctunnel] ERROR: Handshake Error
```
Server Terminal:
```
ctunnel 0.8 Copyright (C) 2008-2020 Jess Mahan
[ctunnel] ctunnel 0.8 starting
[ctunnel] UDP [OpenSSL] VPN using aes-128-cfb
[ctunnel] PtP Pool Local Address 10.0.5.1
[ctunnel] UDP Waiting
[ctunnel] Connect request from 192.168.122.181
[ctunnel] Host asas-Standard-PC-Q35-ICH9-2009[192.168.122.181] -> 10.0.5.2 now has ID 2
Segmentation fault
```

**Comment by alienrobotarmy** [comment]
Please provide command  line arguments for both commands
