### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by vinyldarkscratch** [alienrobotarmy/ctunnel#3]
As stated in https://github.com/Homebrew/homebrew-core/issues/22563, the website hosting a release for this is reporting 404 errors, and attempting to connect to www.nardcore.org (which is the only other mirror I see) is taking forever to load.  Any chance that either site could be fixed?

**Comment by alienrobotarmy** [comment]
https://github.com/Homebrew/homebrew-core/pull/22658
