### ISSUE TITLE
Ctunnel help

### ISSUE THREAD

**Issue by surereddy** [alienrobotarmy/ctunnel#4]
Hello sir
I'm trying to use ctunnel but its not working for me can you kindly help me 

Server 
ctunnel -H 127.0.0.1 -s -l 2222 -f 2221 -C aes-256-cfb
ctunnel 0.7 Copyright (C) 2008-2014 Jess Mahan
Must specify hostname:port

ctunnel -l localhost:22:aes-128-cfb -f 10.0.0.1:22:rc4 -s
ctunnel 0.7 Copyright (C) 2008-2014 Jess Mahan
Enter Key [16 Characters]:

cannot run it.Please help

**Comment by alienrobotarmy** [comment]
Try:
ctunnel  -s -l 127.0.0.1:2222 -f 10.0.0.1:2221 -C aes-256-cfb
