### ISSUE TITLE
bad cidr to mask conversion, got 255.255.255.129 instead of 128

### ISSUE THREAD

**Issue by momiji** [alienrobotarmy/ctunnel#7]
For example, if I use /25 cidr, i got 255.255.255.129 instead if 128. Because compute is done on 255 power instead of 256, evident after you have the nose on it :)

net.c
pow = 256 * pow (instead of 255)
msk = 256 - ... (instead of 255)

**Comment by alienrobotarmy** [comment]
I believe this is fixed.
